# Generated by Django 2.2 on 2020-07-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200711_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(max_length=500),
        ),
    ]
